name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Jekyll
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Build and Deploy
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build
        bundle exec jekyll serve

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
